### ISSUE TITLE
get specific Format and FrameDescriptors

### ISSUE THREAD

**Issue by lobsteroh** [openpnp/libuvc4j#8]
Hi, I am trying to iterate through all available streamformats and all frameformats inside, similar to what happens in uvc_print_diag, but i only seem to get the first instance of each with ... 

```
public static void listAllFrameDescriptors(Pointer<uvc_device_handle> devh, int formatIndex, int frameIndex) throws Exception {
    Pointer<uvc_format_desc> fmtDescPtr = UvcLibrary.uvc_get_format_descs(devh);
    uvc_format_desc fmtDesc = fmtDescPtr.get(formatIndex);
    System.out.println(fmtDesc.bDescriptorSubtype());
    uvc_frame_desc frameDesc = fmtDesc.frame_descs().get(frameIndex);
    System.out.println(frameDesc.bDescriptorSubtype() + "; w: " + frameDesc.wWidth() + "; h: " + frameDesc.wHeight() + " ");
}
```

i am only managing to get the first instance of each by calling

```
listFrameDescriptor(devh,0,0)
```

any index other than 0 fetches trouble.

any suggestions or examples on how to do this correctly are greatly welcome

**Comment by vonnieda** [comment]
Sorry Robert, I don't have a good answer for you. I have not tried to do
what you are doing yet.

Make sure you are checking for null in your fmtDescPtr.get(formatIndex), as
this will return null at the end of the list. Same for the
fmtDesc.frame_descs().get(frameIndex); call.

Jason

**Comment by lobsteroh** [comment]
this is why i am thinking that there is an issue with passing the list back. it looks to me that it is only passing back the first instance. checking for null works just fine with the devices in the device list but not here ... 

```
fmtDescPtr.get(formatIndex);
```

never returns null. even if i ask it to give me index 100, which definitely does not exist, it proceeds past a null check and then reports

```
UVC_VS_UNDEFINED
```

java.lang.RuntimeException: Unaligned pointer access !
    at org.bridj.JNI.get_int(Native Method)
    at org.bridj.Pointer$OrderedPointer.getIntAtOffset(Pointer.java:317)
    at org.bridj.StructIO.getEnumField(StructIO.java:224)
    at org.openpnp.libuvc4j.uvc_frame_desc.bDescriptorSubtype(uvc_frame_desc.java:56)
    at com.lobsterman.JavaGrinders.control.UVCDeviceManager.listFrameDescriptor(UVCDeviceManager.java:144)
    at com.lobsterman.JavaGrinders.control.UVCDeviceManager.main(UVCDeviceManager.java:467)

there is a booboo in there somewhere, but i can't see it.

**Comment by vonnieda** [comment]
Hi Robert,

I suggest writing a C program that does the same thing and link it against
the same version of the library and make sure your base assumptions are
correct that way. If that works then you have a path to debugging the Java
wrappers. Sorry I can't help more with this, I'm swamped with too many
other things right now and this library is low on the priority list for at
least a couple more weeks.

Jason

**Comment by lobsteroh** [comment]
hi jason, thanks a huge stack for your responses. i will see what i can plug together. strategy makes sense, but C is not one of my strengths, especially arrays and passing handlers and pointers into routines is a part i have not dealt with much in Java, and i think this is where the issue lies. it is not holding me up but it is an important enough element of the library. it would be good to have it working and i will look into the how the bridge deals with the different structures. it is clearly working for the device list, but not the other two ... i will see whether i find anything obvious. be well and thanks again, Robert
